db:
  build: Dockers/db
  ports:
    # ext:int port.
    - "5435:5432"
web:
  build: .
  command: python manage.py runserver 0:8000
  volumes:
    - .:/home/docker/{{project_name}}
  ports:
    # ext:int port.
    - "8005:8000"
  links:
    # Define all containers for easy running of development setup.
    - db
